#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../library/_env"

USERNAME=$1
ORG=$2
REPO=$3
COLLABORATOR=$4

"$HERE/api" "$USERNAME" PUT "repos/$ORG/$REPO/collaborators/$COLLABORATOR" '{}'
