#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../library/_env"

USERNAME=$1
PASSWORD=$2
ORG=$3

"$HERE/api" "$USERNAME" "$PASSWORD" \
	POST \
	orgs \
	"{\"username\": \"$ORG\"}"
