#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../library/_env"

USERNAME=$1
PASSWORD=$2
ORG=$3
REPO=$4

"$HERE/api" "$USERNAME" "$PASSWORD" \
	POST \
	"orgs/$ORG/repos" \
	"{\"name\": \"$REPO\", \"default_branch\": \"main\"}"
