#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

CLUSTER=$1

DASHBOARD_CONTAINER_PORT=${DASHBOARD_CONTAINER_PORT:-30000}

# https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
# https://computingforgeeks.com/how-to-install-kubernetes-dashboard-with-nodeport/

if [ ! -f "$HERE/work/dashboard.yaml" ]; then
	mkdir --parents "$HERE/work/"
	curl https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml --output "$HERE/work/dashboard.yaml"
fi

cp "$HERE/work/dashboard.yaml" "$HERE/work/$CLUSTER.yaml"

# Use HTTP node port
replace_text "$HERE/work/$CLUSTER.yaml" 40 42 \
"  type: NodePort
  ports:
    - targetPort: 9090
      port: 80
      nodePort: $DASHBOARD_CONTAINER_PORT"

# Configure cluster name (seen in web browser title)
insert_text "$HERE/work/$CLUSTER.yaml" 92 \
"data:
  _global: '{\"clusterName\": \"$CLUSTER\"}'"

# Enable HTTP and skip authentication
# See: https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md
replace_text "$HERE/work/$CLUSTER.yaml" 203 203 \
"            - --insecure-bind-address=0.0.0.0
            - --enable-skip-login
            - --disable-settings-authorizer"

#replace_text "$HERE/work/$CLUSTER-dashboard.yaml" 223 223 \
#"            timeoutSeconds: 60"

# Add "cluster-admin" permissions
# See: https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges
echo "
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: kubernetes-dashboard-admin
  namespace: kubernetes-dashboard

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard" >> "$HERE/work/$CLUSTER.yaml"

kubectl apply -f "$HERE/work/$CLUSTER.yaml"
