#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"
. "$ROOT/library/_trap"

kubectl patch configs.imageregistry.operator.openshift.io/cluster --type=merge --patch='{"spec":{"managementState":"Managed","storage":{"emptyDir":{}}}}'
