#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

kubectl apply -f "https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v$CONFIG_SYNC_VERSION/config-sync-manifest.yaml"

m 'waiting for Config Sync to start...'
kubectl wait deployment/reconciler-manager --namespace=config-management-system --for=condition=Available --timeout=1h
