#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
	echo "Run this script as root"
	exit 1
fi

# These should be installed already: git jq xdg-utils

dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

dnf install git jq xdg-utils docker-ce docker-ce-cli containerd.io

usermod -aG docker $SUDO_USER

systemctl enable docker

echo 'Reboot your OS!'
