#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
	echo "Run this script as root"
	exit 1
fi

# See: https://docs.docker.com/engine/install/fedora/

# Remove other/old versions of docker
dnf remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-selinux docker-engine-selinux docker-engine || true

dnf install --assumeyes dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

# Note: these should be installed already: git jq xdg-utils
dnf install --assumeyes git jq xdg-utils docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

usermod --append --groups docker "$SUDO_USER"

systemctl enable --now docker

echo 'Reboot your OS!'
