#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

MINIKUBE_VERSION=$(github_version kubernetes/minikube)
MINIKUBE_VERSION=${MINIKUBE_VERSION:1}
m "MINIKUBE_VERSION=$MINIKUBE_VERSION"

KIND_VERSION=$(github_version kubernetes-sigs/kind)
KIND_VERSION=${KIND_VERSION:1}
m "KIND_VERSION=$KIND_VERSION"

KUBECTL_VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
KUBECTL_VERSION=${KUBECTL_VERSION:1}
m "KUBECTL_VERSION=$KUBECTL_VERSION"

OC_VERSION=$(github_version okd-project/okd)
m "OC_VERSION=$OC_VERSION"

KPT_VERSION=$(github_version_of GoogleContainerTools/kpt v)
KPT_VERSION=${KPT_VERSION:1}
m "KPT_VERSION=$KPT_VERSION"

KUBEVIRT_VERSION=$(github_version kubevirt/kubevirt)
KUBEVIRT_VERSION=${KUBEVIRT_VERSION:1}
m "KUBEVIRT_VERSION=$KUBEVIRT_VERSION"

MULTUS_VERSION=$(github_version k8snetworkplumbingwg/multus-cni)
MULTUS_VERSION=${MULTUS_VERSION:1}
m "MULTUS_VERSION=$MULTUS_VERSION"

CERT_MANAGER_VERSION=$(github_version cert-manager/cert-manager)
CERT_MANAGER_VERSION=${CERT_MANAGER_VERSION:1}
m "CERT_MANAGER_VERSION=$CERT_MANAGER_VERSION"

# ROOK_VERSION=$(github_version rook/rook)
# ROOK_VERSION=${ROOK_VERSION:1}
# m "ROOK_VERSION=$ROOK_VERSION"

K9S_VERSION=$(github_version derailed/k9s)
K9S_VERSION=${K9S_VERSION:1}
m "K9S_VERSION=$K9S_VERSION"

HELM_VERSION=$(github_version helm/helm)
HELM_VERSION=${HELM_VERSION:1}
m "HELM_VERSION=$HELM_VERSION"

# DASEL_VERSION=$(github_version TomWright/dasel)
# DASEL_VERSION=${DASEL_VERSION:1}
# m "DASEL_VERSION=$DASEL_VERSION"

YQ_VERSION=$(github_version mikefarah/yq)
YQ_VERSION=${YQ_VERSION:1}
m "YQ_VERSION=$YQ_VERSION"

PORCH_VERSION=$(github_version_of GoogleContainerTools/kpt porch/v)
PORCH_VERSION=${PORCH_VERSION:7}
m "PORCH_VERSION=$PORCH_VERSION"
