#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"

NAMESPACE=$1
REPOSITORY=$2
PACKAGE_NAME=$3
REVISION=$4

if [ -n "$REVISION" ]; then
	if [ "$REVISION" == draft ]; then
		kubectl get packagerevision \
			--field-selector="spec.repository=$REPOSITORY,spec.packageName=$PACKAGE_NAME" \
			--namespace="$NAMESPACE" \
			--output=jsonpath='{.items[0].metadata.name}' 2> /dev/null
	else
		kubectl get packagerevision \
			--field-selector="spec.repository=$REPOSITORY,spec.packageName=$PACKAGE_NAME,spec.revision=$REVISION" \
			--namespace="$NAMESPACE" \
			--output=jsonpath='{.items[0].metadata.name}' 2> /dev/null
	fi
else
	kubectl get packagerevision \
		--field-selector="spec.repository=$REPOSITORY,spec.packageName=$PACKAGE_NAME" \
		--selector=kpt.dev/latest-revision=true \
		--namespace="$NAMESPACE" \
		--output=jsonpath='{.items[0].metadata.name}' 2> /dev/null
fi

echo
