#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

# https://docs.gitea.io/en-us/install-on-kubernetes/

kubectl create namespace gitea || true
helm repo add gitea-charts https://dl.gitea.io/charts/
helm install gitea gitea-charts/gitea --namespace=gitea \
	--set='ingress.hosts[0].host=gitea-http.gitea:3000' || true
