#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"

USERNAME=$1
PASSWORD=$2
NAME=$3
EMAIL=$4
DIR=$5
ORG=$6
REPO=$7

TEMP_DIR=$(mktemp --directory)
cp --recursive "$DIR"/* "$TEMP_DIR/"
git -C "$TEMP_DIR" init --initial-branch=main
git -C "$TEMP_DIR" config user.name "$NAME"
git -C "$TEMP_DIR" config user.email "$EMAIL"
git -C "$TEMP_DIR" add .
git -C "$TEMP_DIR" commit --message='Initial commit'
git -C "$TEMP_DIR" remote add origin "http://$USERNAME:$PASSWORD@$(hostname):32100/$ORG/$REPO.git"
git -C "$TEMP_DIR" push --force --set-upstream origin main
rm --recursive --force "$TEMP_DIR"
