#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

"$HERE/admin/create-user" administrator administrator@gitea password --admin || true
