#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

. "$HERE/_env"

"$HERE/admin/create-user" "$ADMINISTRATOR_USERNAME" administrator@gitea "$ADMINISTRATOR_PASSWORD" --admin || true
