#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"
. "$ROOT/library/_trap"
. "$HERE/_env"

GIT_HOST="http://$(hostname):32100" GIT_USERNAME="$GIT_USERNAME" GIT_DEPLOYMENT_REPO="$GIT_DEPLOYMENT_REPO" GIT_BLUEPRINTS_REPO="$GIT_BLUEPRINTS_REPO" envsubst_dir "$HERE/assets" "$HERE/work"

"$ROOT/platforms/kind/start" management edge1

m 'setting up management cluster...'

"$ROOT/platforms/kind/use" management

"$ROOT/workloads/gitea/deploy"
"$ROOT/workloads/gitea/admin/create-user" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_EMAIL" || true
"$ROOT/workloads/gitea/admin/create-user-repository" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_DEPLOYMENT_REPO" || true
"$ROOT/workloads/gitea/admin/create-user-repository" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_BLUEPRINTS_REPO" || true

# Note: Porch requires the repositories to have at least one commit
"$ROOT/workloads/gitea/git-init" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_NAME" "$GIT_EMAIL" "$HERE/work/deployment-repository" "$GIT_USERNAME" "$GIT_DEPLOYMENT_REPO"
"$ROOT/workloads/gitea/git-init" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_NAME" "$GIT_EMAIL" "$HERE/work/blueprints-repository" "$GIT_USERNAME" "$GIT_BLUEPRINTS_REPO"

"$ROOT/workloads/porch/deploy"
#"$ROOT/workloads/porch-ui/deploy"

kubectl create namespace porch-demo || true

kubectl create secret generic gitea \
    --namespace=porch-demo \
    --type=kubernetes.io/basic-auth \
    --from-literal=username="$GIT_USERNAME" \
    --from-literal=password="$GIT_PASSWORD" || true

kubectl apply -f "$HERE/work/porch-repositories.yaml"

m 'setting up edge1 cluster...'

"$ROOT/platforms/kind/use" edge1

"$ROOT/workloads/config-sync/deploy"

"$ROOT/platforms/kind/use" management
