#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"

kubectl get secret admin --namespace=headlamp --output=jsonpath='{.data.token}' | base64 --decode
echo
