#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

kubectl apply \
    -f "$HERE/assets/crds.yaml" \
    -f "$HERE/assets/common.yaml" \
    -f "$HERE/assets/operator-openshift.yaml" \
    -f "$HERE/assets/dashboard-external-https.yaml" || true
