#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

URL=https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph

function fetch () {
    wget "$URL/$1.yaml" -O "$HERE/assets/$1.yaml"
}

#fetch crds
#fetch common
#fetch operator-openshift
#fetch cluster-test
#fetch dashboard-external-https
#fetch csi/cephfs/storageclass
#fetch filesystem-test
