#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"

IP=$(kubectl get service --selector=app=rook-ceph-mon --namespace=openshift-storage --output=jsonpath={.items[0].spec.clusterIP})

kubectl exec deployment/rook-ceph-operator --namespace=openshift-storage -- \
curl "$IP:3300" 2>/dev/null
