#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

# See: https://github.com/nephio-project/one-summit-22-workshop/

USERNAME=developer
PASSWORD=password

if [ "$1" == -c ]; then
	rm --recursive --force "$HERE/nephio-system"
fi

if [ ! -d "$HERE/nephio-system" ]; then
    kpt pkg get --for-deployment https://github.com/nephio-project/nephio-packages.git/nephio-system "$HERE/nephio-system"
fi

"$HERE/../gitea/admin/create-user" "$USERNAME" "$USERNAME@gitea" password || true
"$HERE/../gitea/admin/api" administrator PATCH "admin/users/$USERNAME" "{\"login_name\":\"$USERNAME\", \"allow_create_organization\":true}"
"$HERE/../gitea/admin/create-org" "$USERNAME" nephio
"$HERE/../gitea/admin/create-repository" "$USERNAME" nephio organizational-blueprints
"$HERE/../gitea/admin/create-repository" "$USERNAME" nephio team-blueprints
"$HERE/../gitea/admin/create-repository" "$USERNAME" nephio edge1-deployments
"$HERE/../gitea/admin/create-repository" "$USERNAME" nephio edge2-deployments

kubectl create namespace nephio || true

m 'creating Gitea secret...'
kubectl create secret generic gitea \
    --namespace=nephio \
    --type=kubernetes.io/basic-auth \
    --from-literal=username="$USERNAME" \
    --from-literal=password="$PASSWORD" || true

m 'deploying Porch repositories...'
kubectl apply -f "$HERE/repositories.yaml"

m 'deploying Nephio CRDs...'
kubectl apply -f "$HERE/nephio-system/package-deployment-controller/crds/"

m 'deploying Package Deployment Controller...'
kubectl create namespace nephio-system || true
kubectl apply -f "$HERE/nephio-system/package-deployment-controller/app/controller/"

m 'creating Nephio clusters...'
kubectl apply -f "$HERE/clusters.yaml"
