#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

kubectl delete --ignore-not-found=true --filename="https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/reloader.yaml"
