#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../_env"
. "$ROOT/library/_trap"
. "$HERE/_env"

# See: https://github.com/GoogleCloudPlatform/anthos-config-management-samples/tree/main/config-sync-quickstart/multirepo).
"$ROOT/workloads/gitea/git-init" "$GIT_USERNAME" "$GIT_PASSWORD" "$GIT_NAME" "$GIT_EMAIL" "$HERE/work/deployment-repository" "$GIT_USERNAME" "$GIT_REPO"

"$ROOT/platforms/kind/use" edge1

kubectl apply -f "$HERE/work/root-sync.yaml"
