#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../library/_env"
. "$ROOT/library/_trap"

NODE_PORT=${NODE_PORT:-30000}

NODE_PORT="$NODE_PORT" envsubst < "$HERE/assets/skooner.yaml" | kubectl apply -f -

m "admin token (from \"$HERE/admin-token\"):"
"$HERE/admin-token"
